version: '3.7'

services:
  gqlgen-example:
    build:
      context: .
      dockerfile: ./docker/server/dev.Dockerfile
    env_file: .env
    volumes:
      - .:/go/src/github.com/jjjjackson/gqlgen-example
      - gomod:/go/pkg/mod
    networks:
      - default
    ports:
      - 3333:3333
    depends_on:
      - db

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  gomod:
  db-data:
