version: '3.7'

services:
  gqlgen-example:
    build: 
      context: .
      dockerfile: ./docker/server/dev.Dockerfile
    env_file: .env
    volumes:
      - .:/go/src/github.com/jjjjackson/gqlgen-example
      - gomod:/go/pkg/mod
    networks:
      - default
    ports:
      - 3333:3333

volumes:
  gomod:
  db-data:
